### ISSUE TITLE
/otr-start doesn't work

### ISSUE THREAD

**Issue by nogoegst** [twstrike/coyim#413]
I've traced it to that `conversationManager` returns `nil` as conversation. This fails anything afterwards and `coyim` exits (without a panic or so).

**Comment by olabini** [comment]
Thanks for tracing it down. We will take a look - the CLI part hasn't received as much love as the GUI components.

**Comment by olabini** [comment]
Actually, would you mind pointing to the line of code where this is happening?

**Comment by nogoegst** [comment]
Does it work for you?
https://github.com/twstrike/coyim/blob/master/cli/ui.go#L713

**Comment by olabini** [comment]
I'm having another problem with the CLI on Linux right now - for some reason the terminal control doesn't seem to work correctly at the moment - I'm not sure if this is a sideeffect of Wayland or something else. You don't see something similar?

**Comment by nogoegst** [comment]
Yes, this bug was already fixed upstream (https://github.com/golang/go/issues/17364) but not fetched here.
btw Wayland has nothing to do with cli.

**Comment by olabini** [comment]
Thanks for the pointer! i've fixed this now - we sadly missed it when it came.
When it comes to what Wayland touches and what it doesn't, I've seen some very weird things, so I didn't exclude it as a possibility. Anyway, thanks for the pointer - I'll look at the real issues now.

**Comment by nogoegst** [comment]
Terminal problem is gone. Though `/otr-start` issue persists for me.

**Comment by olabini** [comment]
That's strange. I just tried /otr-start and that works fine.

**Comment by nogoegst** [comment]
I removed all the repos and refetched `coyim` via
```
go get -v -u -tags cli github.com/twstrike/coyim
```
And this doesn't work as it didn't. I guess it's the same issue as before. Can you test it somewhere else?

**Comment by nogoegst** [comment]
Just for the record, it behave the same way even if arguments are invalid:
```
/otr-start 43243242
```

**Comment by olabini** [comment]
That's extremely strange. The problem had nothing to do with the ConversationManager - the problem was that the i18n package wasn't initialized correctly for the cli. Can you see whether your github.com/twstrike/coyim/cli.go contains a line with:
    i18n.InitLocalization(i18n.NoLocal)
?

**Comment by nogoegst** [comment]
I can't imagine how it could work for you. `CommandManager` was never set for a session thus failing due to `nil` pointer reference. So any command that used `ExecuteCmd` would lead to this.
See PR https://github.com/twstrike/coyim/pull/416
P.S. It was so hard to find... why everything is so complicated? Could it be without all these endless adapters and interfaces? :S

**Comment by olabini** [comment]
I'm sorry, but CommandManager was never used for /otr-start and for the message commands. It's only used when you make changes that will update the configuration file - so I'm a bit confused how you hit that code with /otr-start.

**Comment by olabini** [comment]
Anyway, thanks for finding the problem.
